#from .views_lab9 import company_list,company_detail,vacancy_by_company,vacancy_list,vacancy_detail,vacancy_top_ten
#from .views_fbv import company_list,company_detail,vacancy_by_company,vacancy_list,vacancy_detail,vacancy_top_ten
from .views_cbv import CompanyListAPIView,CompanyDetailAPIView,VacancyByCompany,VacancyListAPIView,VacancyDetailAPIView,TopTenVacanciesView