# Generated by Django 3.2.18 on 2023-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the discipline', max_length=1000)),
                ('prereq', models.TextField(help_text='Enter a prerequisite of the discipline', max_length=1000)),
            ],
        ),
    ]
